### ISSUE TITLE
Transform and recompile function

### ISSUE THREAD

**Issue by dfdx** [jrevels/Cassette.jl#109]
Let's say, we have a function like this: 

```
logistic(x) = 1 / (1 + exp(-x))
```
we want to change some detail in it, say, make it compatible with CuArrays: 

```
logistic(x) = 1 / (1 + CUDAnative.exp(-x))
```
We can do it with a custom Cassette pass, but as far as I understand, we will have to call it as: 

```
ctx = CustomContext(pass=custom_pass)
@overdub ctx logistic(x)
```
In other words, we transform function execution, not the function itself. Such execution has its price both - in terms of runtime and usage. 

In Yota.jl, I'm playing around with [another approach](https://github.com/dfdx/Yota.jl/tree/cuda-example#tape-transformations--function-rewriting): I record function execution on a tape, transform it and then recompile it back. As a result I can write: 

```
cu_logistic = cuda_compatible(logistic, 1.0)
```
Now `cu_logistic` can be used just like any other function without performance penalty or explicit context. The drawback of this approach is that recompiled function can be pretty different from the original, e.g. all loops are unrolled, conditional branches are fixed, etc. 

Is it possible to make a more gentle transformation that would return a normal function without requiring a context?

**Comment by jrevels** [comment]
There are multiple directions I could go here depending on your question, but I'm not sure I fully understand what exactly is being asked yet. I'll just make some assumptions, though, and see where that takes us 😛 

First, you could implement `cu_logistic(x)` via a Cassette pass like:

```
cu_logistic(x) = overdub(CustomContext(pass=custom_pass), logistic, x)
```

Side note: if your transform is really just method replacement, you don't need a custom pass; you can just overload contextual primitives w.r.t. `CustomContext`. 

> In other words, we transform function execution, not the function itself. Such execution has its price both - in terms of runtime and usage.

> I record function execution on a tape, transform it and then recompile it back

I think this is where I'm confused a bit. Is the intent here to compare JIT compile-time IR passes with a "staged" taping approach? Cassette facilitates both kinds of implementations, and each approach has it's own advantages/disadvantages.

The main advantage of injecting IR passes via Cassette is that the passes are executed at compile time, so their application does not require separate front-end stages ("record -> transform -> recompile"). Additionally, these passes have access to information that is not generally exposed as part of taping implementation (e.g. non-executed code paths, IR elements that are otherwise hard to reach, etc.). Conversely, the "attack surface" that IR passes are required to cover can be quite large, and there's a steep learning curve - feeding IR directly to Julia's compiler is often trickier than feeding it the equivalent Julia code via the normal front-end. 

The main advantage of taping via Cassette is that you don't have to deal with that large attack surface if you don't need the extra information that surface exposes. It's also usually pretty easy to implement, since you can use normal Julia front-end mechanisms (e.g. operator overloading) without needing to interact directly with the compiler (since Cassette handles that for you). However, you then have the burden of figuring out how to "stage" downstream transformations + recompilation, instead of having your transformation occur as part of the normal JIT compile cycle.

Either approach requires talking about contexts, but from an API perspective there's usually no need to expose contexts to users (e.g. Yota's `trace` function).

Does any of this help? Sorry if I rambled and missed the mark!

**Comment by jrevels** [comment]
Reading back, I think I could provide a better answer if I had a better understood your exact meaning of: 

```
Such execution has its price both - in terms of runtime and usage.
```

If the user calls `cu_logistic(x)` either way, there's no "usage" change vs. a taping approach, right? In terms of runtime - the passes are applied at compile time, and so (in theory) should be amortized over multiple executions (like Julia's compilation in general). 

If you're seeing any runtime overhead from applying a pass (that was not just introduced via the pass itself), then that sounds like a performance bug to be fixed :)

**Comment by dfdx** [comment]
> In terms of runtime - the passes are applied at compile time, and so (in theory) should be amortized over multiple executions (like Julia's compilation in general).

I think this was the source of my confusion, although now it looks obvious. Perhaps I need to switch "contextual execution" to "contextual compilation" in my mind when thinking about performance :)

Thanks for the detailed answer! I will review my comment and come back with further questions if any.

**Comment by dfdx** [comment]
Ok, I think I have nothing more to ask, at least for now. Thanks again for your help!
