### ISSUE TITLE
Tracing Julia code execution via Cassette?

### ISSUE THREAD

**Issue by robertfeldt** [jrevels/Cassette.jl#96]
I'm considering different ways of implementing execution tracing of Julia code (so that I can save variable information after each line is executed etc) . It seems that implementing this with Cassette.jl might be one option (my base alternative is to rewrite the Julia code to be traced via accessing the AST/Exprs). 

Has anyone seen examples of doing something similar with Cassette.jl? 

If not, do you think it is a suitable use case? 

Thanks for any input you might have.

**Comment by vchuravy** [comment]
Cassette is the way to go, since it allows for princinpled and recursive
transformation of Julia IR. Depending on what you need/want to achieve the
part of Cassette you want to use is the support for IR passes.

I wrote a non-trivial tool with Cassette a while ago
https://github.com/vchuravy/ConcolicFuzzer.jl which had to trace variables
and manipulate IR.

**Comment by oxinabox** [comment]
depending exactly what you want, you might not need to using IR transform.
You can use overdub, (esp prehook and posthook) to do the tracing at the function invocation level.
And since most interesting parts of a program are executing functions, that could be enough.

(Main loss is variable names)

**Comment by robertfeldt** [comment]
Thanks to both of you. This is really helpful. I need to trace the execution of each statement and of variable values so it sounds like overdub might not be enough.

**Comment by jpfairbanks** [comment]
I had a similar question and this answered it. As a follow up, is there a minimal compiler pass implemented somewhere? The one in the docs (see #93) is a little complex for beginners. I am happy to contribute to the docs with a simpler minimum example. I think an example that just captures the variable names and values into the context would be really helpful.

Since the main difference between using overdub vs a custom pass is access to variable names, I would guess a lot of people writing passes would benefit from an example that showed how to capture variable names.

**Comment by vchuravy** [comment]
The one at
https://github.com/vchuravy/ConcolicFuzzer.jl/blob/master/src/asserts.jl is
fairly simply. It has the goal of finding all conditional branches (loops
and ifs) and mark them.

**Comment by oxinabox** [comment]
This one might well be want you want.
https://github.com/oxinabox/MagneticReadHead.jl/pull/14
